// 库存数据 - 每次更新Excel后重新生成此文件
const DATA = {
  updated: '2026-04-20',
  summary: { total: 518, phone: 293, watch: 148, ipad: 66, mac: 11 },
  phone: [
    { series: 'iPhone 17 Pro Max', variant: '银色 256GB', qty: 31, status: 'green', tag: '主推' },
    { series: 'iPhone 17 Pro Max', variant: '银色 512GB', qty: 23, status: 'green', tag: '' },
    { series: 'iPhone 17 Pro Max', variant: '星宇橙 256GB', qty: 18, status: 'green', tag: '' },
    { series: 'iPhone 17 Pro Max', variant: '星宇橙 512GB', qty: 15, status: 'green', tag: '' },
    { series: 'iPhone 17 Pro Max', variant: '深蓝 256GB', qty: 9, status: 'orange', tag: '' },
    { series: 'iPhone 17 Pro Max', variant: '深蓝 512GB', qty: 1, status: 'red', tag: '控货' },
    { series: 'iPhone 17 Pro Max', variant: '银色 1TB', qty: 1, status: 'red', tag: '控货' },
    { series: 'iPhone 17', variant: '白色 256GB', qty: 31, status: 'green', tag: '主推' },
    { series: 'iPhone 17', variant: '黑色 256GB', qty: 24, status: 'green', tag: '主推' },
    { series: 'iPhone 17', variant: '薰衣草紫 256GB', qty: 22, status: 'green', tag: '女性首选' },
    { series: 'iPhone 17', variant: '青雾蓝 256GB', qty: 9, status: 'orange', tag: '' },
    { series: 'iPhone 17', variant: '鼠尾草绿 256GB', qty: 7, status: 'orange', tag: '' },
    { series: 'iPhone 17', variant: '其他小容量', qty: 3, status: 'orange', tag: '' },
    { series: 'iPhone 17 Pro', variant: '星宇橙/银 256GB', qty: 32, status: 'green', tag: '主推' },
    { series: 'iPhone 17 Pro', variant: '银色 512GB', qty: 15, status: 'green', tag: '' },
    { series: 'iPhone 17 Pro', variant: '深蓝 256GB', qty: 6, status: 'orange', tag: '' },
    { series: 'iPhone 17 Pro', variant: '深蓝 512GB', qty: 2, status: 'orange', tag: '' },
    { series: 'iPhone Air', variant: '浅金 256GB', qty: 10, status: 'green', tag: '注意：仅256G' },
    { series: 'iPhone Air', variant: '天蓝 256GB', qty: 7, status: 'orange', tag: '' },
    { series: 'iPhone Air', variant: '深空黑 256GB', qty: 6, status: 'orange', tag: '' },
    { series: 'iPhone Air', variant: '云白 256GB', qty: 5, status: 'orange', tag: '' },
    { series: 'iPhone 17e', variant: '黑/白 256GB', qty: 10, status: 'red', tag: '紧缺控货' },
  ],
  watch: [
    { series: 'Watch Series 11', variant: '银色+雾紫 42mm', qty: 22, status: 'green', tag: '主推' },
    { series: 'Watch Series 11', variant: '玫瑰金+粉 42mm', qty: 20, status: 'green', tag: '' },
    { series: 'Watch Series 11', variant: '亮黑+黑 46mm', qty: 18, status: 'green', tag: '' },
    { series: 'Watch Series 11', variant: '灰+黑 46mm', qty: 17, status: 'green', tag: '' },
    { series: 'Watch Series 11', variant: '玫瑰金+粉 46mm', qty: 16, status: 'green', tag: '' },
    { series: 'Watch Series 11', variant: '亮黑+黑 42mm', qty: 15, status: 'green', tag: '' },
    { series: 'Watch Series 11', variant: '灰+黑 42mm', qty: 14, status: 'orange', tag: '' },
    { series: 'Watch SE', variant: '星光 40mm', qty: 10, status: 'green', tag: '' },
    { series: 'Watch SE', variant: '午夜 44mm', qty: 7, status: 'orange', tag: '' },
    { series: 'Watch SE', variant: '星光 44mm', qty: 2, status: 'orange', tag: '' },
    { series: 'Watch Ultra 49mm', variant: '原色', qty: 1, status: 'red', tag: '按需调货' },
  ],
  ipad: [
    { series: 'iPad 标准版 第11代', variant: '深空灰 256GB', qty: 12, status: 'green', tag: '主推' },
    { series: 'iPad 标准版 第11代', variant: '银色 256GB', qty: 9, status: 'orange', tag: '' },
    { series: 'iPad 标准版 第11代', variant: '银色 128GB', qty: 8, status: 'orange', tag: '' },
    { series: 'iPad 标准版 第11代', variant: '粉色 128GB', qty: 6, status: 'orange', tag: '' },
    { series: 'iPad 标准版 第11代', variant: '深空灰 128GB', qty: 5, status: 'orange', tag: '' },
    { series: 'iPad 标准版 第11代', variant: '蓝色 256GB', qty: 4, status: 'orange', tag: '' },
    { series: 'iPad 标准版 第11代', variant: '粉色 256GB', qty: 4, status: 'orange', tag: '' },
    { series: 'iPad 标准版 第11代', variant: '蓝色 128GB', qty: 3, status: 'orange', tag: '' },
    { series: 'iPad Pro', variant: '银色 256GB', qty: 5, status: 'orange', tag: '' },
    { series: 'iPad Pro', variant: '深空黑 256GB', qty: 4, status: 'orange', tag: '' },
    { series: 'iPad mini 第7代', variant: '紫色/灰色 128GB', qty: 2, status: 'red', tag: '转推iPad11' },
    { series: 'iPad Air 第8代', variant: '深空灰 256GB', qty: 1, status: 'red', tag: '紧急补货' },
  ],
  mac: [
    { series: 'MacBook Air', variant: '各配置', qty: 8, status: 'green', tag: '' },
    { series: 'Mac mini', variant: '各配置', qty: 2, status: 'orange', tag: '' },
    { series: 'MacBook Pro', variant: '各配置', qty: 1, status: 'red', tag: '转推Air' },
  ],
  push: [
    { model: 'iPhone 17 Pro Max', variant: '银色 256GB', qty: 31, col: '#0051D4' },
    { model: 'iPhone 17', variant: '白色 256GB', qty: 31, col: '#0051D4' },
    { model: 'iPhone 17 Pro', variant: '星宇橙/银 256GB', qty: 32, col: '#E67E22' },
    { model: 'iPhone 17', variant: '黑色 256GB', qty: 24, col: '#0051D4' },
    { model: 'iPhone 17', variant: '薰衣草紫 256GB', qty: 22, col: '#0051D4' },
    { model: 'Watch S11', variant: '银色+雾紫 42mm', qty: 22, col: '#8E44AD' },
    { model: 'Watch S11', variant: '玫瑰金+粉 42mm', qty: 20, col: '#8E44AD' },
    { model: 'iPad 第11代', variant: '深空灰 256GB', qty: 12, col: '#E37400' },
  ],
  warn: [
    { model: 'iPad Air 第8代', status: '仅剩 1 台', sev: 'red', action: '立即申请补货' },
    { model: 'iPad mini 第7代', status: '仅剩 2 台', sev: 'red', action: '转推 iPad 第11代' },
    { model: 'iPhone 17e 全系', status: '仅剩 10 台', sev: 'red', action: '控货，引导17/17Pro' },
    { model: 'Watch Ultra 49mm', status: '仅剩 1 台', sev: 'red', action: '按需调货' },
    { model: 'MacBook Pro', status: '仅剩 1 台', sev: 'red', action: '转推 MacBook Air' },
    { model: 'iPhone 16 全系', status: '仅剩 1 台', sev: 'orange', action: '停止主推，下架' },
  ]
};
